### PR TITLE
Update sha256sums

### PR DESCRIPTION
**Pull request by leonardoInf**
The sha256sum for multiple sources is outdated and one source url is wrong.

### CODE REVIEW

**Comment by WinterMute** [comment]
Can you stop updating stuff now please. None of this will be merged.

We're no longer using the archives you're updating sha256sums for and you're making changes we don't want. Sorry.

**Comment by leonardoInf** [comment]
ok, no problem

**Comment by leonardoInf** [comment]
ok, no problem

**Comment by leonardoInf** [comment]
ok, no problem

**Comment by leonardoInf** [comment]
@WinterMute as you have censored me by deleting my issue I will state my opinion clearly here. You are just doing useless cosmetic changes to this unusable repository which does not even have a free software license to keep your patrons happy by implying that you are actually developing open software here. I acknowledge that you are a very good programmer but I can not accept your behaviour. Just delete this repository.

**Pull request closed without merging**
